config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  root 'home#index'
  get  '/flash_close' => 'home#flash_close'
  get  '/contact'     => 'home#contact'
  get  '/about'       => 'home#about'

  scope :flower_sitter do
    get '/agreement'             => 'home#fs_agreement'
    post '/agreement_check'      => 'home#agreement_check'
    get '/welcome'               => 'home#fs_welcome'
    post '/first_create'         => 'home#first_create'
    get '/congrats/:id'          => 'home#fs_congrats'
  end

  resources :cards

  resources :users, except: :index

  resources :rooms

  resources :messages

  get '/portfolio' => 'home#portfolio'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :icon

  has_many :cards, dependent: :destroy

  has_many :sitter_rooms, class_name: 'Room', foreign_key: 'sitter_id', dependent: :destroy

  has_many :guest_rooms,  class_name: 'Room', foreign_key: 'guest_id', dependent: :destroy

  has_many :sitter, through: :guest_rooms, source: 'guest'

  has_many :guest,  through: :sitter_rooms, source: 'sitter'

  has_many :messages

  before_create :set_default_icon

  def set_default_icon
    self.icon.attach(io:File.open(Rails.root.join('app', 'assets', 'images', 'default-icon.png')), filename: 'default-icon.png', content_type: 'image/png')
    # user.icon.attach(io: File.open('/app/assets/images'), filename: 'default.svg', content_type: 'icon/svg')
  end

  def unread_messages_count(user_id)
    count = 0
    self.sitter_rooms.each do |room|
      count += room.messages.where.not("(has_read = ?) OR (user_id = ?)", true, user_id).count
    end

    self.guest_rooms.each do |room|
      count += room.messages.where.not("(has_read = ?) OR (user_id = ?)", true, user_id).count
    end

    count
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @room = Room.new
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :profile, :icon)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_flower_sitter.html.erb
<div class="users-sitter-card-area">
  <div class="flower-sitter">フラワーシッター</div>
  <div class="table-box">
    <%= image_tag(user.cards.first.image, class: 'card-image') %>
    <div class="detail-box">
      <div class="card-title"><%= user.cards.first.title %></div>
      <div class="card-price">料金／日: ¥120</div>
      <div class="link-area">
        <% if user_signed_in? && current_user == user %>
          <%= link_to '編集', edit_card_path(user.cards.first.id), class: 'to-edit btn btn-info btn-sm'%>
        <% end %>
        <%= link_to '依頼・質問ページへ', card_path(user.cards.first.id), class: 'to-show btn btn-primary btn-sm' %>
      </div>
    </div>
  </div>
  <div class="card-description"><%= simple_format(user.cards.first.description) %></div>
</div>

app/views/users/edit.html.erb
<%= render 'layouts/header' %>

<div class="edit-area">
  <div class="edit-box">
    <%= form_with model: @user, url: user_path, method: :patch, local: true, class: 'form-group' do |form| %>
      <div class="yes-no-area">
        <%= link_to '戻る', @user, class: 'btn btn-outline-secondary btn-cancel' %>
        <%= form.submit "完了", class: "btn btn-outline-primary btn-done" %>
      </div>

      <div class="icon-box">
        <%= image_tag(@user.icon, class: 'icon') if @user.icon.attached? %>
      </div>
      <div class="icon-preview"></div>
      <div class="input-group">
        <label class="btn-icon">
        <span class="btn btn-outline-primary btn-icon">
          アイコンを選択
          <%= form.file_field :icon, accept: 'image/jpg,image/jpeg,image/png', class: 'btn-icon', style: 'display: none' %>
        </span>
        </label>
      </div>
      <%= form.label :name, '名前' %>
      <%= form.text_field :name, class: "form-control" %>

      <%= form.label :email, 'メールアドレス ※変更できません' %>
      <%= form.text_field :email, readonly: true, class: "form-control" %>

      <%= form.label :profile, 'プロフィール' %>
      <%= form.text_area :profile, class: "form-control profile", value: @user.profile, placeholder: "自己紹介" %>
    <% end %>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
    $(document).on('change', ':file', function() {
        var input = $(this),
            numFiles = input.get(0).files ? input.get(0).files.length : 1,
            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.parent().parent().next(':text').val(label);

        var files = !!this.files ? this.files : [];
        if (!files.length || !window.FileReader) return; // no file selected, or no FileReader support
        if (/^image/.test( files[0].type)){ // only image file
            var reader = new FileReader(); // instance of the FileReader
            reader.readAsDataURL(files[0]); // read the local file
            reader.onloadend = function(){ // set image data as background of div
                // input.parent().parent().parent().prev('.imagePreview').css("display", "inline-block");
                // input.parent().parent().parent().prev('.imagePreview').css("background-image", "url("+this.result+")");
                // input.parent().parent().parent().prev('.icon').css("display", "inline-block");
                input.parent().parent().parent().prev('.icon-preview').css("background-image", "url("+this.result+")");
            }
        }
    });
</script>

app/views/users/show.html.erb
<%= render 'layouts/header' %>
<div class="user-area">
  <div class="user-box">
    <div class="icon-frame">
      <%= image_tag(@user.icon, class: 'icon') if @user.icon.attached? %>
    </div>
    <div class="name"><%= @user.name %></div>
    <div class="email"><%= @user.email if user_signed_in? and @user == current_user %></div>
    <div class="profile"><%= simple_format(@user.profile) %></div>
    <%= link_to 'プロフィール編集', edit_user_path, class: 'btn btn-edit' if user_signed_in? and @user == current_user %>
  </div>
  <% unless @user.cards.first.nil? %>
    <%= render 'users/flower_sitter', { user: @user } %>
  <% end %>
</div>

<%= render 'layouts/users_under', { user: current_user } %>