config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  root 'home#index'
  get  '/flash_close' => 'home#flash_close'
  get  '/contact'     => 'home#contact'
  get  '/about'       => 'home#about'

  scope :flower_sitter do
    get '/agreement'             => 'home#fs_agreement'
    post '/agreement_check'      => 'home#agreement_check'
    get '/welcome'               => 'home#fs_welcome'
    post '/first_create'         => 'home#first_create'
    get '/congrats/:id'          => 'home#fs_congrats'
  end

  resources :cards

  resources :users, except: :index

  resources :rooms

  resources :messages

  get '/portfolio' => 'home#portfolio'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :flash_close, :contact, :about, :portfolio]

  def index
  end

  def flash_close
  end

  def contact
  end

  def about
  end

  def fs_agreement
    if current_user && current_user.sitter_status == 1
      redirect_to welcome_path
    elsif current_user && current_user.sitter_status == 2
      redirect_to root_path
    else

    end
  end

  def agreement_check
    if params[:agreement] == '0'
      render 'fs_agreement'
    else
      current_user.update_attributes(sitter_status: 1) if current_user.sitter_status == 0
      redirect_to welcome_path
    end
  end

  def fs_welcome
    if current_user && current_user.sitter_status == '1'

    elsif current_user && current_user.sitter_status == '2'
      redirect_to root_path
    end
  end

  def first_create
    @card = Card.new(welcome_params)
    if @card.save
      current_user.update_attributes(sitter_status: 2) if current_user.sitter_status == 1
      redirect_to "/flower_sitter/congrats/#{@card.id}"
    else
      render 'fs_welcome'
    end
  end

  def fs_congrats
    @card = Card.find(params[:id])
  end

  def portfolio

  end

  private

  def welcome_params
    params.require(:card).permit(:title, :description, :price, :user_id, :image)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_example_area.html.erb
<div class="example-area">
  <ul class="horizontal-list">
    <li class="item">
      <div></div>
    </li>
    <li class="item">
      <div></div>
    </li>
    <li class="item">
      <div></div>
    </li>
    <li class="item">
      <div></div>
    </li>
  </ul>
</div>

app/views/home/_qna.html.erb
<div class="container">
  <div class="qna-area row justify-content-center">
    <div class="col-10 h4 qna-title">よくある質問</div>
    <div class="col-10 qna-item">
      <div class="qna-q border-bottom">どんな植物を預かってもらえますか？</div>
      <div class="qna-a">基本的にどんな植物でも可能です。しかし、植物によって大きさや必要な知識は様々なのでフラワーシッター（預かってくれる方）にご確認ください。</div>
    </div>
    <div class="col-10 qna-item">
      <div class="qna-q border-bottom">お支払い方法は？</div>
      <div class="qna-a">植物を預けるとき、または引き取りの際に支払います。　また、現金やクレジットカードなど支払い手段はフラワーシッター（預かってくれる方）にご確認ください。</div>
    </div>
<!--    <div class="col-10 qna-item">-->
<!--      <div class="qna-q border-bottom">Hey Siri, 明日の天気は?</div>-->
<!--      <div class="qna-a">すみません。よくわかりません。</div>-->
<!--    </div>-->
  </div>
</div>

app/views/home/_review_for_flower_sitter.html.erb
<div class="review-for-flower-sitter-area">
  <div class="top-box">
    <div class="sub-title">〜フラワーシッターに預みて〜</div>
    <div class="title">ゲストのみなさんの声</div>
  </div>
  <div class="reviewer-box">
    <div class="comment-area">
      <div class="icon-frame">
        <%= image_tag('flower-sitter-1.jpg', class: 'icon') %>
      </div>
      <div class="text">
        <div class="text-tag-head">“</div>
        <div class="description">
          Pellentesque habitant morbi tristique senectus. Vestibulum tortor quam, feugiat vitae, ultricies ege...
        </div>
        <div class="text-tag-end">”</div>
        <div class="country">イカタコ駅前店</div>
      </div>
    </div>
  </div>
</div>

app/views/home/_usage_flow.html.erb
<div class="usage-flow-area">
  <div class="usage-flow-box">
    <div class="title">ご利用の流れ</div>
    <div class="usage-item">
      <div class="illustration fas fa-search"></div>
      <div class="text">まずは、預かり可能なフラワーシッターを探します。</div>
      <%= link_to('フラワーシッターを探す', cards_path, class: '') %>
    </div>
    <div class="usage-item">
      <div class="illustration far fa-comments"></div>
      <div class="text">お願いしたいフラワーシッターが見つかれば、フラワーシッターのページより「依頼・質問」ボタンをタップすると、メッセージを送ることが可能になります。預かってもらいたい植物が受け入れ可能か、そのほか日程やご料金などについてもメッセージにて、フラワーシッターにご確認ください。</div>
    </div>
    <div class="usage-item">
      <div class="illustration far fa-handshake"></div>
      <div class="text">ゲストのご要望や日程、ご料金などフラワーシッターとご相談の上、受け入れを確定します。</div>
    </div>
    <div class="usage-item">
      <div class="illustration fas fa-people-carry"></div>
      <div class="text">約束の日時に植物をフラワーシッターのところまで持ち込みます。返却日を確認の上、植物を預けて完了です。</div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<%= render 'layouts/header' %>
<div class="about-area">
  <h1 class="about-h1">Broccolliについて</h1>
  <div class="about-box">
    Broccolliは、植物を一時的に預けたい人と預かってくれる人を繋ぐオンラインサービスです。
    <br/>短期から長期まで、旅行や出張で自宅から離れるの間、あなたの植物を守るお手伝いをします。
  </div>
  <div class="team-box">
    <h5>チームメンバー</h5>
    <div class="member-box">
      <%= image_tag('ueno.jpg', class: 'member-pic') %>
      <div class="member-text">
        上野 元輝<br/>
        企画・開発
      </div>
    </div>
    <div class="member-box">
      <%= image_tag('matsumoto.jpg', class: 'member-pic') %>
      <div class="member-text">
        松本 一寿<br/>
        立案・マーケティング
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/home/contact.html.erb
<% provide(:title, '近くのシッターに植物を預かってもらうサービス｜Broccolli 問い合わせ') %>
<% provide(:description, 'ご質問やご要望はこちらよりお待ちしております。') %>
<% provide(:keywords, '') %>

<%= render 'layouts/header' %>
<div class="contact-area">
  <div class="box">
    <div class="icon-area">
      <div class="icon far fa-envelope"></div>
      <div class="icon-text">お問い合わせ</div>
    </div>
    <div class="text-box">
      <div class="text">
        当サービスに対するご意見・ご要望などがございましたら、下記メールアドレス宛にお気軽にお問い合わせください。
      </div>
      <div class="email">
        broccolli.info@gmail.com
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/home/flash_close.js.erb
$("#flash-close").hide();

app/views/home/fs_agreement.html.erb
<%= render 'layouts/header' %>

<div>フラワーシッターとは？</div>
<br/>
<div>フラワーシッターはユーザーの植物を一時的に預かってくれる人々です</div>
<div>預かっている期間は、定期的な水やりなど簡易なお世話をします</div>

<br/>
<div class="agreement-area">
  <%= render 'home/agreement/terms_of_service' %>
</div>

<div class="btn-area">
  <%= form_with url: agreement_check_path, method: :post, local: true, class: 'form-check' do |form| %>
    <%= form.check_box :agreement %>
    <%= form.label :agreement, '同意する' %>
    <%= form.submit 'はじめる', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/home/fs_congrats.html.erb
<%= render 'layouts/header' %>
<div class="container congrats-area">
  <div class="row">
    <div class="text-box">
      <div class="title">おめでとうございます!!</div>
      <div class="sub-title">植物を預かる準備が整いました</div>
    </div>
    <div class="btn-box">
      <%= link_to 'マイページ', user_path(current_user), class: 'btn btn-success w-75' %>
      <%= link_to 'Topに戻る', root_path, class: 'btn btn-secondary w-75' %>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/home/fs_welcome.html.erb
<%= render 'layouts/header' %>
<div class="container welcome-area">
  <div class="top">
    <div class="user-name"><%= current_user.name %>さん</div>
    <div class="title">ようこそ！<br/>フラワーシッターへ</div>
    <div class="sub-title">ユーザーがあなたを見つけられるように宣伝しよう</div>
  </div>
  <%= form_with model: current_user.cards.build, url: first_create_path, method: :post, local: true, class: 'form-group' do |form| %>
    <%= form.label :title, 'タイトル' %>
    <%= form.text_field :title, required: true, placeholder: '例：東京駅すぐ　イカタコ・ワンダフル南口店です！',class: 'form-control' %>
    <br/>
    <%#= form.label :preImagePreview, '画像' %>
    <%#= form.text_field :preImagePreview, required: true, readonly: true, placeholder: '未選択', class: 'form-control preImagePreview' %>
    <div class="imagePreview"></div>
    <div class="input-group">
      <label class="btn-image">
        <span class="btn btn-primary btn-image">
          画像を選択
          <%= form.file_field :image, accept: 'image/jpg,image/jpeg,image/png', required: true, class: 'btn-image', style: 'display: none' %>
        </span>
      </label>
<!--      <input type="text" class="form-control" readonly="">-->
    </div>
    <br/>
    <%= form.label :description, '説明文' %>
    <%= form.text_area :description, required: true,
                       placeholder: '例：大阪府ブロッコリー市駅前のフラワーショップ、Broccoli駅前店です！　知識豊富なスタッフが皆さんのお花や観葉植物を一時的にお預かり致します。お気軽にご連絡ください ♪　定休日：水曜日　※水曜日の受付・返却はできません',
                       class: 'form-control description-form' %>
    <br/>
    <%= form.label :price, '料金/日' %>
    <%= form.number_field :price, value: '0', require: true, class: 'form-control' %>
    <br/>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.submit '完了', class: 'btn btn-primary btn-done' %>
  <% end %>
</div>
<%= render 'layouts/footer' %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
    $(document).on('change', ':file', function() {
        var input = $(this),
            numFiles = input.get(0).files ? input.get(0).files.length : 1,
            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.parent().parent().next(':text').val(label);

        var files = !!this.files ? this.files : [];
        if (!files.length || !window.FileReader) return; // no file selected, or no FileReader support
        if (/^image/.test( files[0].type)){ // only image file
            var reader = new FileReader(); // instance of the FileReader
            reader.readAsDataURL(files[0]); // read the local file
            reader.onloadend = function(){ // set image data as background of div
                input.parent().parent().parent().prev('.imagePreview').css("display", "inline-block");
                input.parent().parent().parent().prev('.imagePreview').css("background-image", "url("+this.result+")");
            }
        }
    });
</script>

app/views/home/index.html.erb
<% provide(:title, '近くのシッターに植物を預かってもらうサービス｜Broccolliトップページ') %>
<% provide(:description, '') %>
<% provide(:keywords, '植物,預ける,サービス,お花,購入,') %>
<%= render 'layouts/header' %>
<div class="pic-area">
  <%= image_tag('top-bg3.jpg', class: 'top-background-sp sp') %>
  <%= image_tag('top-bg6.jpg', class: 'top-background-pc pc') %>
  <div class="pc-top-bg-cover pc"></div>
  <div class="container main-title-box">
    <div class="row justify-content-center my-3">
      <div class="col-11 main-content pt-3 pb-5">
        <div class="sub-title py-2 text-center"></div>
        <div class="title">
          植物を想う、 生活を。
        </div>
        <div class="btn-area">
          <%= link_to('はじめる', cards_path, class: 'btn btn-secondary btn-top border-0') %>
        </div>
      </div>
    </div>
  </div>
  <div class="section-box">
    <div class="text-box-1">
      <div class="title">お家のお花や観葉植物に新しい選択肢を。</div>
      <div class="sub-title">Broccolliは、植物を一時的に預けたい人と預かってくれる人を繋ぐオンラインサービスです。短期から長期まで、旅行や出張で自宅から離れるのときにあなたの植物を守るお手伝いをします。</div>
      <%= link_to('フラワーシッターを探す', cards_path, class: 'btn btn-secondary btn-top border-0') %>
    </div>
  </div>

  <%#= render 'home/example_area' %>

  <div class="middle-pic-area">
    <%= image_tag('middle-3.jpg', class: 'pic') %>
  </div>

  <div class="section-box">
    <div class="text-box-2">
      <div class="title">フラワーシッターとは？</div>
      <div class="sub-title">一時的にあなたがお持ちの植物たちを預かってくれる人々です。お預かりの間はゲストの要望通りに水やりなどのお世話を行います。</div>
      <%= link_to('フラワーシッターになる', agreement_path, class: 'btn btn-primary border-0') %>
    </div>
  </div>

  <%= render 'home/review_for_flower_sitter' %>

</div>

<%= render 'home/usage_flow' %>

<%= render 'home/qna' %>

<%= render 'layouts/footer' %>

<%= render 'layouts/users_under', { user: current_user } %>

app/views/home/portfolio.html.erb
<div class="portfolio-area">
  <div class="portfolio-box">
    <div class="title">学習内容/ポートフォリオ</div>
    <div class="content">
      ・基礎学習<br/>
      Progate(HTML CSS JavaScript jQuery Ruby Ruby on Rails コマンドライン Git)<br/>
      ドットインストール(sinatra入門)<br/>
      Sinatraを使った小さなWebアプリ作成<br/>
      Udemy(よくわかるRuby on Rails 入門 RubyとRailsを基礎から学びWebアプリケーションをネットに公開しよう ) <br/>
      Railsチュートリアル(2周)<br/>
      書籍「ゼロからわかるRuby入門」<br/>
      書籍「プロになるためのWeb技術入門」<br/>
      書籍「ちゃんと使える力を身につけるWebとプログラミングのきほんのきほん」<br/>
      書籍「Railsの教科書」<br/>
      書籍「Bootstrap4 フロントエンド開発の教科書」<br/>
      書籍「たのしいRuby 第5版」<br/>
      書籍「現場で使えるRuby on Rails5速習実践ガイド」<br/>
      <br/>
      自作ポートフォリオ<br/>
      ■ホストOS: MacOS<br/>
      ■言語: HTML CSS JavaScript Ruby SQL<br/>
      ■フレームワーク: Ruby on Rails<br/>
      ■CSSフレームワーク: bootstrap<br/>
      ■JSライブラリ: jQuery<br/>
      ■サーバー: heroku<br/>
      ■その他ツールなど: Git Bitbucket clubhouse<br/><br/>
      ・以前お世話になったアルバイト先に特化した在庫管理＆勤怠管理を目的とした社内アプリケーションの作成(PCでの利用を想定した仕様なのでPCもしくはタブレットでご覧いただけますと幸いです)<br/>
      サービス名: セントラル・キッチン<br/>
      URL: <%= link_to 'アプリケーションサイトへ', "https://central-kitchen.herokuapp.com/users/sign_in" %><br/>
      Bitbucket: <%= link_to 'https://bitbucket.org/genki_ueno/central_kitchen-made-by-gu/src/master/', "https://bitbucket.org/genki_ueno/central_kitchen-made-by-gu/src/master/" %><br/><br/>
      ・自宅で育てているお花や観葉植物を一時的に預かって欲しい人と預かってくれる人を繋ぐオンラインサービ ス<br/>
      サービス名: ブロッコリー<br/>
      URL: <%= link_to 'サービスページへ（PC用レイアウトは作成中のため、モバイルレイアウトでご覧いただけますと幸いです）', "https://www.broccolli.jp" %><br/><br/>
      ・写真投稿SNS開発(Instagramクローン)<br/>
      [サイトURL]<br/>
      <%= link_to 'https://instagram-lesson-local.herokuapp.com/', 'https://instagram-lesson-local.herokuapp.com/' %><br/>
      [BitbucketURL]<br/>
      <%= link_to 'https://bitbucket.org/genki_ueno/instagram-lesson-ueno/src /master/', 'https://bitbucket.org/genki_ueno/instagram-lesson-ueno/src /master/' %><br/>
    </div>
  </div>
</div>