config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  root 'home#index'
  get  '/flash_close' => 'home#flash_close'
  get  '/contact'     => 'home#contact'
  get  '/about'       => 'home#about'

  scope :flower_sitter do
    get '/agreement'             => 'home#fs_agreement'
    post '/agreement_check'      => 'home#agreement_check'
    get '/welcome'               => 'home#fs_welcome'
    post '/first_create'         => 'home#first_create'
    get '/congrats/:id'          => 'home#fs_congrats'
  end

  resources :cards

  resources :users, except: :index

  resources :rooms

  resources :messages

  get '/portfolio' => 'home#portfolio'
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :user_id, :title, :description, :price, :image, presence: true

  # def self.ransackable_attributes(auth_object = nil)
  #   %w[title description]
  # end
  #
  # def self.ransackable_associations(auth_object = nil)
  #
  # end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update]

  def index
    @q = Card.all.ransack(params[:q])
    @cards = @q.result(distinct: true)
  end

  def create
  end

  def show
    @card = Card.find(params[:id])
    @room = Room.new
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    if @card.update_attributes(cards_params)
      flash[:success] = "更新しました"
      redirect_to @card
    else
      render 'edit'
    end
  end

  private

  def cards_params
    params.require(:card).permit(:title, :image, :description, :price, :user_id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_broccolli.html.erb
<div class="col-6 col-sm-3 box my-2 px-1">
  <div class="content rounded">
    <div class="image-box rounded">
      <%= link_to image_tag(card.image, class: 'image rounded', alt: card.user.name + 'の画像'), card if card.image.attached? %>
    </div>
    <div class="text rounded-bottom">
      <div class="sitter-area">
        <%= link_to image_tag(card.user.icon, class: 'sitter-icon'), card.user if card.user.icon.attached? %>
        <%= link_to card.user.name, card.user, class: 'sitter-name' %>
      </div>
      <div class="title"><%= card.title %></div>
      <div class="description"><%= card.description %></div>
    </div>
  </div>
</div>

app/views/cards/edit.html.erb
<%= render 'layouts/header' %>
<div class="container card-edit-area">
  <%= form_with model: @card, url: card_path(@card.id), method: :patch, local: true, class: 'form-group' do |form| %>
    <%= form.label :title, 'タイトル' %>
    <%= form.text_field :title,
                        required: true,
                        value: @card.title,
                        placeholder: '例：東京駅すぐ　イカタコ・ワンダフル南口店です！',
                        class: 'form-control' %>
    <br/>
    <div class="image-area">
      <div class="image-box">
        <%= image_tag(@card.image, class: 'image') if @card.image.attached? %>
      </div>
      <div class="imagePreview"></div>
      <div class="input-group">
        <label class="btn-image">
        <span class="btn btn-primary btn-image">
          画像を選択
          <%= form.file_field :image, accept: 'image/jpg,image/jpeg,image/png', class: 'btn-image', style: 'display: none' %>
        </span>
        </label>
      </div>
    </div>
    <br/>
    <%= form.label :description, '説明文' %>
    <%= form.text_area :description, required: true,
                       value: @card.description,
                       placeholder: '例：大阪府ブロッコリー市駅前のフラワーショップ、Broccoli駅前店です！　知識豊富なスタッフが皆さんのお花や観葉植物を一時的にお預かり致します。お気軽にご連絡ください ♪　定休日：水曜日　※水曜日の受付・返却はできません',
                       class: 'form-control description-form' %>
    <br/>
    <%= form.label :price, '料金/日' %>
    <%= form.number_field :price,
                          value: @card.price,
                          require: true,
                          class: 'form-control' %>
    <br/>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.submit '完了', class: 'btn btn-primary btn-done' %>
  <% end %>
</div>
<%= render 'layouts/footer' %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
    $(document).on('change', ':file', function() {
        var input = $(this),
            numFiles = input.get(0).files ? input.get(0).files.length : 1,
            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.parent().parent().next(':text').val(label);

        var files = !!this.files ? this.files : [];
        if (!files.length || !window.FileReader) return; // no file selected, or no FileReader support
        if (/^image/.test( files[0].type)){ // only image file
            var reader = new FileReader(); // instance of the FileReader
            reader.readAsDataURL(files[0]); // read the local file
            reader.onloadend = function(){ // set image data as background of div
                input.parent().parent().parent().prev('.imagePreview').css("background-image", "url("+this.result+")");
            }
        }
    });
</script>

app/views/cards/index.html.erb
<% provide(:title, 'フラワーシッター検索｜Broccolli 植物を預かってもらうサービス') %>
<% provide(:description, 'Broccolliは自宅の植物を近くのお花屋さんや植物が好きな人、詳しい人(フラワーシッター)に預かってもらうための日本初マッチングサービスです。こちらから近くのフラワーシッターを探しましょう！') %>
<% provide(:keywords, '') %>

<%= render 'layouts/header' %>
<%= search_form_for @q, url: cards_path, class: '' do |f| %>
  <div class="row justify-content-center" id="search-area">
    <div class="">
      <%= f.search_field :title_or_description_cont_all,
                         placeholder: '地名、駅など',
                         class: 'form-control search-window' %>
    </div>
    <div class="">
      <%= button_tag :type => "submit", :class =>"btn btn-search" do %>
        <i class="fa fa-search"></i>
      <% end %>
    </div>
  </div>
<% end %>
<div class="text-area">
  <div class="sub-title">フラワーシッター</div>
  <div class="title">お花や観葉植物のお預け先</div>
</div>
<div class="container cards-index-area">
  <div class="row cards-area no-gutters">
    <%= render partial: 'cards/broccolli', collection: @cards, as: :card %>
    <% if @cards.blank? %>
      <div class="no-result-area">
        <div class="text">見つかりませんでした。</div>
      </div>
    <% end %>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/cards/show.html.erb
<%= render 'layouts/header' %>
<div class="card-area">
  <div class="image-box">
    <%= image_tag(@card.image, class: 'image', alt: @card.user.name + 'の画像') %>
    <%= link_to '', cards_path, class: 'btn-back-on-pic fas fa-chevron-circle-left' %>
  </div>
  <div class="text-area">
    <div class="title"><%= @card.title %></div>
    <div class="name-of-sitter-area">フラワーシッター</div>
    <div class="sitter-icon-area">
      <%= link_to @card.user.name, @card.user, class: 'sitter-name' %>
      <%= link_to image_tag(@card.user.icon, class: 'sitter-icon'), @card.user if @card.user.icon.attached? %>
    </div>
    <div class="description"><%= @card.description %></div>
  </div>
  <div class="offer-area">
    <div class="price">1つ¥<%= @card.price %>から</div>
<!--    <div class="loader">Loading</div>-->
    <%= form_with model: user_signed_in? ? current_user.sitter_rooms.build : @room, url: rooms_path, method: :post, local: true, class: 'form-group' do |form| %>
      <%= form.hidden_field :guest_id, value: user_signed_in? ? current_user.id : 0 %>
      <%= form.hidden_field :sitter_id, value: @card.user.id %>
      <%= form.submit '依頼・質問', class: 'btn btn-success btn-offer' unless current_user == @card.user %>
      <%= link_to '編集', edit_card_path(@card.id), class: 'btn btn-info btn-offer' if current_user == @card.user %>
    <% end %>
  </div>
</div>