config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  root 'home#index'
  get  '/flash_close' => 'home#flash_close'
  get  '/contact'     => 'home#contact'
  get  '/about'       => 'home#about'

  scope :flower_sitter do
    get '/agreement'             => 'home#fs_agreement'
    post '/agreement_check'      => 'home#agreement_check'
    get '/welcome'               => 'home#fs_welcome'
    post '/first_create'         => 'home#first_create'
    get '/congrats/:id'          => 'home#fs_congrats'
  end

  resources :cards

  resources :users, except: :index

  resources :rooms

  resources :messages

  get '/portfolio' => 'home#portfolio'
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <footer class="row align-items-center">
    <div class="col text-center">
      Broccolli Services Limited<br>
      ©︎2019 Broccolli. All rights reserved.
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <header class="row align-items-center justify-content-between">
    <div class="col-6 logo-area">
      <%#= link_to image_tag('logo.svg'), root_path, class: 'logo' %>
      <%= link_to 'Broccolli', root_path, class: 'title' %>
    </div>
<!--    <div class="col-1"><%#= link_to image_tag(current_user.icon, class: 'user-icon'), user_path(current_user) if user_signed_in? %></div>-->
    <div class="col-3">
      <div class="dropdown">
        <button class="btn fas fa-bars dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          <% if user_signed_in? %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            <%= link_to 'マイページ', user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'メッセージ', rooms_path, class: 'dropdown-item' %>
            <%#= link_to 'お知らせ', '#', class: 'dropdown-item' %>
            <%= link_to 'フラワーシッターを探す', cards_path, class: 'dropdown-item' %>
            <%= link_to 'フラワーシッターになる', agreement_path, class: 'dropdown-item' %>
            <%= link_to 'よくある質問', '#', class: 'dropdown-item' %>
            <%= link_to 'ブロッコリーについて', about_path, class: 'dropdown-item' %>
            <%= link_to 'お問い合わせ', contact_path, class: 'dropdown-item' %>
        <% else %>
            <%= link_to '新規登録', new_user_registration_path, class: 'dropdown-item'  %>
            <%= link_to 'ログイン', new_user_session_path, class: 'dropdown-item'  %>
            <%#= link_to 'お知らせ', '#', class: 'dropdown-item' %>
            <%= link_to 'よくある質問', '#', class: 'dropdown-item' %>
            <%= link_to 'ブロッコリーについて', about_path, class: 'dropdown-item' %>
            <%= link_to 'お問い合わせ', contact_path, class: 'dropdown-item' %>
        <% end %>
        </div>
      </div>
    </div>
  </header>
</div>

app/views/layouts/_users_under.html.erb
<% if user_signed_in? %>
  <div class="users_under-blank"></div>

  <div class="container fixed-area">
    <div class="row box align-items-center text-center">
      <div class="col item-box">
        <div class="items far fa-arrow-alt-circle-left">
          <%= link_to '', root_path, class: 'link' %>
<!--          <div class="badge">56</div>-->
        </div>
      </div>
      <div class="col item-box">
        <div class="items far fa-comment-alt">
          <%= link_to '', rooms_path, class: 'link' %>
          <% if current_user.unread_messages_count(current_user.id) >= 1 %>
            <div class="badge"><%= current_user.unread_messages_count(current_user.id) %></div>
          <% end %>
        </div>
      </div>
      <%= link_to image_tag(user.icon, class: 'under-icon'), user_path(user), class: 'col' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="Description" content=<%= meta_description(yield(:description)) %>>
    <meta name="Keywords" content=<%= meta_keywords(yield(:keywords)) %>>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert-area">
        <div class="alert alert-<%= message_type %> flash-box" id="flash-close">
          <%= message %><%= link_to '', flash_close_path, remote: true, class: 'fas fa-times flash-close' %>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>